Login = "root"
External = "10.90.36.34"
HostIPs = ["10.90.36.34", "10.90.36.35", "10.90.36.56", "10.90.36.58"]
ProxyAddress = "localhost"
MonitorPort = 10000
Simulation = "ZeroLottery"
Servers = 4
Hosts = 16
Debug = 3
DebugTime = false
DebugColor = false
DebugPadding = true
RunWait = "6000s"
Delay = 100
Bandwidth = 100
Suite = "Ed25519"
PreScript = ""
Tags = ""
