Simulation = "Calypso"
Servers = 1
Bf = 9
Rounds = 1
RunWait =  "600s"
Delay = 100
Bandwidth = 100
Suite = "Ed25519"
BlockInterval  = 10
BlockWait = 10
DebugTime = true

Hosts, NumTransactions
10, 500
10, 500
10, 500
10, 500
10, 500
