Login = "enisalp"
Host = "users.deterlab.net"
Project = "SAFER"
Experiment = "Calypso"
ProxyAddress = "localhost"
MonitorAddress = "users.isi.deterlab.net"
MonitorPort = 10000
Servers = 10
Simulation = "SimpleCalypso"
Hosts = 0
Debug = 0
RunWait = "24000s"
Suite = "Ed25519"
PreScript = ""
Tags = ""
