Simulation = "CentralizedCalypsoByzgen"
Servers = 1
Bf = 1
Rounds = 1
RunWait =  "24000s"
Delay = 100
Bandwidth = 100
Suite = "Ed25519"

Hosts, NumTransactions, NumWriteTransactions, NumReadTransactions
1, 3291, 1821, 1470
