Simulation = "Fully"
Servers = 1
Bf = 1
Rounds = 3
Delay = 100
Bandwidth = 100
RunWait =  "36000s"
Suite = "Ed25519"

Hosts, NumTransactions, NumWriteTransactions, NumReadTransactions
1, 3291, 1821, 1470
